docker run \
	-e SAM_TEMPLATE="${SAM_TEMPLATE}" \
	-e OUTPUT_TEMPLATE_FILE="${OUTPUT_TEMPLATE_FILE}" \
	-e PIPELINE_USER_ACCESS_KEY_ID="${PIPELINE_USER_ACCESS_KEY_ID}" \
	-e PIPELINE_USER_SECRET_ACCESS_KEY="${PIPELINE_USER_SECRET_ACCESS_KEY}" \
	-e PIPELINE_EXECUTION_ROLE="${PIPELINE_EXECUTION_ROLE}" \
	-e CF_STACK_NAME="${CF_STACK_NAME}" \
	-e BITBUCKET_REPO_SLUG="${BITBUCKET_REPO_SLUG}" \
	-e BITBUCKET_DEPLOYMENT_ENVIRONMENT="${BITBUCKET_DEPLOYMENT_ENVIRONMENT}" \
	-e ARTIFACTS_BUCKET="${ARTIFACTS_BUCKET}" \
	-e AWS_REGION="${AWS_REGION}" \
	-e CLOUDFORMATION_EXECUTION_ROLE="${CLOUDFORMATION_EXECUTION_ROLE}" \
	-e SAM_CONFIG_FILE="${SAM_CONFIG_FILE}" \
	-e BITBUCKET_CLONE_DIR="${BITBUCKET_CLONE_DIR}" \
        -e CAPABILITIES="${CAPABILITIES}" \
        -v ${LOCAL_PATH}:${BITBUCKET_CLONE_DIR} \
	gilcesarf/aws-sam-custom-deploy:1.0.0
