#trustep/aws-sam-custom-deploy:1.0.0-$(date "+%Y%m%d-%H%M%S")
name: Pipeline

on:
  push:
    branches:
      - 'feature**'
  delete:
    branches:
      - 'feature**'

env:
  SAM_CLI_TELEMETRY: 0

jobs:
  deploy-feature:
    if: startsWith(github.ref, 'refs/heads/feature') && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          NEXT_RELEASE_BASE_VERSION: ${{ secrets.NEXT_RELEASE_BASE_VERSION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CF_EXECUTION_ROLE: ${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }}
          PIPELINE_EXECUTION_ROLE: ${{ secrets.PIPELINE_EXECUTION_ROLE }}
          SAM_TEMPLATE: template.yaml
          SAM_CONFIG_FILE: samconfig.toml
          OUTPUT_TEMPLATE_FILE: packaged-template.yaml
          PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ARTIFACTS_BUCKET: io.trustep.manager.cf.templates
          CAPABILITIES: CAPABILITY_IAM
          CF_STACK_NAME: aws-sam-custom-deploy
        run: |
         FEATURE_STACK_NAME=$(echo ${FEATURE_BRANCH_NAME##*/} | tr -cd '[a-zA-Z0-9-]')
         BITBUCKET_REPO_SLUG=aws-sam-custom-deploy
         BITBUCKET_DEPLOYMENT_ENVIRONMENT=qa
         ARTIFACTS_BUCKET_PREFIX="${BITBUCKET_DEPLOYMENT_ENVIRONMENT}/${BITBUCKET_REPO_SLUG}/${CF_STACK_NAME}" \
         BITBUCKET_CLONE_DIR=/project
         LOCAL_PATH=$(pwd)/test/docker/resources
         IMAGE="${BITBUCKET_REPO_SLUG}:${NEXT_RELEASE_BASE_VERSION}-feat-${FEATURE_BRANCH_NAME}"
         cd src/main/docker
         docker build . --file Dockerfile --tag "${IMAGE}"
         cd ../../..
         docker run --rm \
           -e SAM_TEMPLATE="${SAM_TEMPLATE}" \
           -e OUTPUT_TEMPLATE_FILE="${OUTPUT_TEMPLATE_FILE}" \
           -e PIPELINE_USER_ACCESS_KEY_ID="${PIPELINE_USER_ACCESS_KEY_ID}" \
           -e PIPELINE_USER_SECRET_ACCESS_KEY="${PIPELINE_USER_SECRET_ACCESS_KEY}" \
           -e PIPELINE_EXECUTION_ROLE="${PIPELINE_EXECUTION_ROLE}" \
           -e CF_STACK_NAME="${CF_STACK_NAME}" \
           -e BITBUCKET_REPO_SLUG="${BITBUCKET_REPO_SLUG}" \
           -e BITBUCKET_DEPLOYMENT_ENVIRONMENT="${BITBUCKET_DEPLOYMENT_ENVIRONMENT}" \
           -e ARTIFACTS_BUCKET="${ARTIFACTS_BUCKET}" \
           -e ARTIFACTS_BUCKET_PREFIX="${BITBUCKET_DEPLOYMENT_ENVIRONMENT}/${BITBUCKET_REPO_SLUG}/${CF_STACK_NAME}" \
           -e AWS_REGION="${AWS_REGION}" \
           -e CF_EXECUTION_ROLE="${CF_EXECUTION_ROLE}" \
           -e SAM_CONFIG_FILE="${SAM_CONFIG_FILE}" \
           -e BITBUCKET_CLONE_DIR="${BITBUCKET_CLONE_DIR}" \
           -e CAPABILITIES="${CAPABILITIES}" \
           -v ${LOCAL_PATH}:${BITBUCKET_CLONE_DIR} \
           "${IMAGE}"

  undeploy-feature:
    if: startsWith(github.event.ref, 'feature') && github.event_name == 'delete'
    uses: trustep/io.trustep.github.workflows/.github/workflows/sam-undeploy-pipeline.yaml@main
    with:
      stack_name: ${{needs.setup-vars.outputs.FEATURE_STACK_NAME}}
      pipeline_execution_role_arn: ${{needs.setup-vars.outputs.TESTING_PIPELINE_EXECUTION_ROLE}}
      artifacts_s3_bucket_name: ${{needs.setup-vars.outputs.TESTING_ARTIFACTS_BUCKET}}
      region: ${{needs.setup-vars.outputs.TESTING_REGION}}
      sam_config_filename: ${{needs.setup-vars.outputs.SAM_CONFIG_FILENAME}}
      sam_config_environment_name: QA
    secrets: inherit